//! Project-local Rust crate initialization and script scaffolding.
//!
//! This module owns filesystem-neutral authoring rules such as names, stable
//! component IDs, the deterministic module index, and non-destructive project
//! initialization. GUI code remains a thin caller.
//!
//! Everything below `assets/scripts/rust/` is one Rust module tree. Folders are
//! free-form: the folder path becomes the Rust module path, and what a source
//! declares (component, resource, system, or an ordinary helper module) is
//! decided by the attributes in the source itself, never by its folder.

use crate::component_metadata::{
    component_metadata_path, load_component_metadata, write_component_metadata, ComponentMetadata,
    ComponentMetadataError,
};
use crate::persist::{replace_file_contents, PersistError};
use crate::ProjectRoot;
use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};

/// Kind of Rust gameplay source generated by the editor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RustScriptKind {
    /// A typed runtime ECS component with authoring schema metadata.
    Component,
    /// A typed project-wide host-owned runtime resource.
    Resource,
    /// A project-local ECS system.
    System,
    /// An ordinary Rust module without engine declarations.
    SharedModule,
}

impl RustScriptKind {
    /// Returns the recommended creation folder below `assets/scripts/rust/`.
    ///
    /// The folder is a default destination only. A created source may be moved
    /// to any other folder below the Rust script root without changing what it
    /// declares.
    pub fn recommended_folder(self) -> &'static str {
        match self {
            Self::Component => "components",
            Self::Resource => "resources",
            Self::System => "systems",
            Self::SharedModule => "shared",
        }
    }
}

/// Recommended folders created below `assets/scripts/rust/`.
///
/// These are the default destinations of the editor's create commands. They are
/// never enforced: any folder below the Rust script root may hold any kind of
/// project Rust source.
pub const RECOMMENDED_RUST_SCRIPT_FOLDERS: [&str; 4] =
    ["components", "resources", "systems", "shared"];

/// Existing runtime schedule selected for a generated system.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RustScriptSchedule {
    /// Per-frame update.
    Update,
    /// Fixed-timestep update.
    FixedUpdate,
}

impl RustScriptSchedule {
    fn attribute_name(self) -> &'static str {
        match self {
            Self::Update => "update",
            Self::FixedUpdate => "fixed_update",
        }
    }
}

/// Engine declaration recognized inside a project Rust source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum RustDeclarationKind {
    /// `GameComponent` derive or `#[game_component(...)]` attribute.
    Component,
    /// `GameResource` derive or `#[game_resource(...)]` attribute.
    Resource,
    /// `#[game_system(...)]` attribute.
    System,
}

impl RustDeclarationKind {
    /// Returns the stable English label used in diagnostics.
    pub fn label(self) -> &'static str {
        match self {
            Self::Component => "component",
            Self::Resource => "resource",
            Self::System => "system",
        }
    }
}

/// One engine declaration found by inspecting a project Rust source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RustDeclaration {
    /// Which engine registration the declaration produces.
    pub kind: RustDeclarationKind,
    /// Declared Rust type name, or function name for a system.
    pub rust_name: String,
    /// Registration ID written in the attribute, when the attribute carries it.
    pub declared_id: Option<String>,
    /// One-based line of the declaration item.
    pub line: usize,
}

/// Classifies a project Rust source by the declarations it contains.
///
/// Detection reads the source text, not the file's folder, so a component stays
/// a component after it is moved anywhere below `assets/scripts/rust/`. Line and
/// block comments are removed before scanning, and multi-line attributes are
/// joined, so commented-out or wrapped declarations are not misread.
///
/// # Examples
///
/// ```
/// use engine_authoring::{rust_declarations, RustDeclarationKind};
///
/// let source = "#[derive(engine::GameComponent)]\npub struct Health { pub value: f32 }\n";
/// let declarations = rust_declarations(source);
/// assert_eq!(declarations[0].kind, RustDeclarationKind::Component);
/// assert_eq!(declarations[0].rust_name, "Health");
/// ```
pub fn rust_declarations(source: &str) -> Vec<RustDeclaration> {
    let stripped = strip_comments(source);
    let lines = stripped.lines().collect::<Vec<_>>();
    let mut declarations = BTreeMap::<usize, RustDeclaration>::new();
    let mut line_index = 0;
    while line_index < lines.len() {
        if !lines[line_index].trim_start().starts_with("#[") {
            line_index += 1;
            continue;
        }
        let attribute = collect_attribute(&lines, line_index);
        if let Some(kind) = attribute_declaration_kind(&attribute.text)
            && let Some((line, rust_name)) = next_declaration(&lines, &attribute, kind)
        {
            // A declaration is usually introduced by a derive and refined by
            // its companion attribute, so the ID may arrive on either one.
            let declared_id = attribute_string_argument(&attribute.text, "id");
            match declarations.get_mut(&line) {
                Some(existing) if existing.declared_id.is_none() => {
                    existing.declared_id = declared_id;
                }
                Some(_) => {}
                None => {
                    declarations.insert(
                        line,
                        RustDeclaration {
                            kind,
                            rust_name,
                            declared_id,
                            line,
                        },
                    );
                }
            }
        }
        line_index = attribute.end_line.saturating_add(1);
    }
    declarations.into_values().collect()
}

/// Initializes the optional project-local Rust crate without overwriting code.
///
/// Existing current-format source and manifests are preserved. Missing
/// recommended folders, the crate-root module index, and ignore rules are
/// added. An existing Cargo host must already use the unified module tree;
/// obsolete per-category hosts are rejected instead of migrated in place.
///
/// # Errors
///
/// Returns an error when an existing host is not in the current layout, when a
/// filesystem operation fails, when a `mod.rs` is present below
/// `assets/scripts/rust/`, or when the module index cannot be generated.
pub fn initialize_game_project(project: &ProjectRoot) -> Result<(), GameProjectError> {
    validate_current_game_host(project)?;

    let game_dir = project.game_dir();
    let mut directories = vec![project.rhai_scripts_dir(), game_dir.join("src")];
    directories.extend(
        RECOMMENDED_RUST_SCRIPT_FOLDERS
            .iter()
            .map(|folder| project.rust_scripts_dir().join(folder)),
    );
    for directory in directories {
        fs::create_dir_all(&directory).map_err(|source| GameProjectError::Io {
            path: directory,
            source,
        })?;
    }
    fs::create_dir_all(game_dir.join(".iroha")).map_err(|source| GameProjectError::Io {
        path: game_dir.join(".iroha"),
        source,
    })?;
    let vscode_dir = project.path().join(".vscode");
    fs::create_dir_all(&vscode_dir).map_err(|source| GameProjectError::Io {
        path: vscode_dir.clone(),
        source,
    })?;

    let cargo_manifest = game_dir.join("Cargo.toml");
    write_if_missing(
        &cargo_manifest,
        "[package]\nname = \"iroha-game\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\ncrate-type = [\"cdylib\"]\n\n[dependencies]\nengine = \"0.1.0\"\n\n[workspace]\n",
    )?;
    ensure_standalone_workspace(&cargo_manifest)?;
    let root_module = game_dir.join("src").join("lib.rs");
    write_if_missing(
        &root_module,
        "//! Internal Cargo host for user-authored sources below `assets/scripts/rust`.\n\ninclude!(\"project_modules.rs\");\n\nengine::export_game_module!();\n",
    )?;
    write_if_missing(&game_dir.join(".gitignore"), "/target/\n/.iroha/\n")?;
    write_if_missing(
        &game_dir.join("README.md"),
        "# Internal Rust Build Host\n\nUser-authored Rust code lives below `../assets/scripts/rust/` and is shown in the Asset Browser. Folders below that root are free-form and become Rust module paths. This crate contains only Cargo integration and the generated `src/project_modules.rs` index; do not move user scripts into `game/src/` and do not add `mod.rs` files below the Rust script root. Open the project in Engine Editor once on each machine so it can refresh the index and write the standard `.cargo/config.toml` SDK path.\n\n## Validate\n\nFrom this `game/` directory run:\n\n```text\ncargo check --all-targets\n```\n",
    )?;
    write_if_missing(
        &vscode_dir.join("settings.json"),
        "{\n  \"rust-analyzer.linkedProjects\": [\n    \"game/Cargo.toml\"\n  ]\n}\n",
    )?;
    refresh_game_module_indexes(project)
}

/// Creates one Rust script in the recommended folder for its kind.
///
/// The source may be moved to any other folder below `assets/scripts/rust/`
/// afterwards.
pub fn create_rust_script(
    project: &ProjectRoot,
    kind: RustScriptKind,
    rust_name: &str,
    schedule: RustScriptSchedule,
) -> Result<PathBuf, GameProjectError> {
    create_rust_script_in(
        project,
        kind,
        Path::new(kind.recommended_folder()),
        rust_name,
        schedule,
    )
}

/// Creates a Rhai source in a folder relative to `assets/scripts/rhai/`.
pub fn create_rhai_script_in(
    project: &ProjectRoot,
    category_folder: &Path,
    file_stem: &str,
) -> Result<PathBuf, GameProjectError> {
    validate_script_folder(category_folder)?;
    let valid_name = !file_stem.is_empty()
        && file_stem
            .chars()
            .all(|character| character == '_' || character.is_ascii_alphanumeric())
        && file_stem
            .chars()
            .next()
            .is_some_and(|character| character == '_' || character.is_ascii_alphabetic());
    if !valid_name {
        return Err(GameProjectError::InvalidName(
            "Rhai file name must start with an ASCII letter or `_` and contain only ASCII letters, digits, or `_`"
                .to_owned(),
        ));
    }
    let path = project
        .rhai_scripts_dir()
        .join(category_folder)
        .join(format!("{file_stem}.rhai"));
    if path.exists() {
        return Err(GameProjectError::DuplicateName(file_stem.to_owned()));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| GameProjectError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    replace_file_contents(
        &path,
        "// Rhai gameplay script.\n\nfn update() {\n    // Add per-frame script behavior here.\n}\n",
    )
    .map_err(GameProjectError::Persist)?;
    Ok(path)
}

/// Creates a Rust script in a folder relative to `assets/scripts/rust/`.
///
/// The folder is free-form; every path segment must be a valid Rust module
/// name because the folder tree becomes the generated module path.
///
/// # Errors
///
/// Returns an error for invalid names or folders, an occupied destination, a
/// module-name collision, or a failed index refresh. Nothing is left on disk
/// when the refresh rejects the new source.
pub fn create_rust_script_in(
    project: &ProjectRoot,
    kind: RustScriptKind,
    script_folder: &Path,
    rust_name: &str,
    schedule: RustScriptSchedule,
) -> Result<PathBuf, GameProjectError> {
    validate_rust_type_name(rust_name)?;
    validate_script_folder(script_folder)?;
    for component in script_folder.components() {
        let name = component.as_os_str().to_string_lossy();
        validate_rust_module_name(&name)
            .map_err(|_| GameProjectError::InvalidScriptFolder(script_folder.to_path_buf()))?;
    }
    initialize_game_project(project)?;
    let file_stem = to_snake_case(rust_name);
    let path = project
        .rust_scripts_dir()
        .join(script_folder)
        .join(format!("{file_stem}.rs"));
    if path.exists() {
        return Err(GameProjectError::DuplicateName(rust_name.to_owned()));
    }
    let (contents, component_metadata) = match kind {
        RustScriptKind::Component => {
            let stable_suffix = ulid::Ulid::new().to_string().to_ascii_lowercase();
            let component_id = format!("game.c_{stable_suffix}");
            let contents = format!(
                "//! `{rust_name}` project component.\n\n/// Editable game data stored on runtime entities.\n///\n/// Stable identity is stored in the adjacent `.rs.meta.json` sidecar and is\n/// preserved when this type or source file is renamed or moved.\n#[derive(Debug, Clone, Default, engine::GameComponent)]\n#[game_component(display_name = \"{rust_name}\")]\npub struct {rust_name} {{\n    /// Example public setting shown in the Inspector.\n    pub enabled: bool,\n}}\n"
            );
            (
                contents,
                Some(ComponentMetadata::new(component_id).map_err(GameProjectError::Metadata)?),
            )
        }
        RustScriptKind::Resource => {
            let resource_id = format!("game.{file_stem}");
            let contents = format!(
                "//! `{rust_name}` project-wide runtime resource.\n\n/// Host-owned Play state shared by project systems.\n///\n/// This value starts from `Default` for every Play generation. It is not\n/// written to scenes or saves unless a system explicitly issues a save command.\n#[derive(Debug, Clone, Default, engine::GameResource)]\n#[game_resource(id = \"{resource_id}\", display_name = \"{rust_name}\")]\npub struct {rust_name} {{\n    /// Example shared runtime setting.\n    pub enabled: bool,\n}}\n"
            );
            (contents, None)
        }
        RustScriptKind::System => {
            let schedule_name = schedule.attribute_name();
            let contents = format!(
                "//! `{rust_name}` project system.\n\nuse engine::prelude::*;\n\n/// Runs on the `{schedule_name}` schedule.\n///\n/// Add typed parameters such as `Time`, `Action<MyAction>`, `Query<MyQuery>`,\n/// `ResMut<MyResource>`, `Events<CollisionEvent>`, or `Commands`. The macro\n/// derives the host access declaration from the exact parameter types.\n#[engine::game_system(\n    id = \"game.{file_stem}\",\n    display_name = \"{rust_name}\",\n    schedule = \"{schedule_name}\"\n)]\nfn {file_stem}() {{}}\n"
            );
            (contents, None)
        }
        RustScriptKind::SharedModule => {
            let contents = format!(
                "//! Ordinary project module `{rust_name}`.\n\n/// Example helper shared by project components, resources, and systems.\npub fn enabled() -> bool {{\n    true\n}}\n"
            );
            (contents, None)
        }
    };
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| GameProjectError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    replace_file_contents(&path, &contents).map_err(GameProjectError::Persist)?;
    if let Some(metadata) = component_metadata {
        let metadata_path = component_metadata_path(&path);
        if let Err(error) = write_component_metadata(&metadata_path, &metadata) {
            let _ = fs::remove_file(&path);
            return Err(GameProjectError::Metadata(error));
        }
    }
    if let Err(error) = refresh_game_module_indexes(project) {
        let _ = fs::remove_file(component_metadata_path(&path));
        let _ = fs::remove_file(&path);
        return Err(error);
    }
    Ok(path)
}

/// Regenerates the Cargo host module index from user sources in assets.
///
/// The complete tree below `assets/scripts/rust/` is validated before anything
/// is written, so a rejected refresh leaves the previous index in place.
///
/// # Errors
///
/// Returns an error for invalid module names, colliding module names, a
/// `mod.rs` below the Rust script root, a symlink, a component source without
/// its sidecar, or duplicated component, resource, and system IDs.
pub fn refresh_game_module_indexes(project: &ProjectRoot) -> Result<(), GameProjectError> {
    let index = build_project_module_index(project)?;
    validate_project_rust_sources(project)?;
    replace_file_contents(&project.game_module_index_path(), &index)
        .map_err(GameProjectError::Persist)
}

/// Moves or renames one project Rust source together with its sidecar.
///
/// Both paths are relative to `assets/scripts/rust/`. A `.rs.meta.json` sidecar
/// is moved with the source when one exists, so a component keeps its stable ID
/// and every scene, prefab, and Inspector reference stays valid.
///
/// Rust `use` paths inside project sources are deliberately not rewritten; the
/// regenerated module index and `cargo check` report the affected lines.
///
/// # Errors
///
/// Returns an error for unsafe paths, a missing source, a destination
/// collision, filesystem failures, or invalid project metadata.
pub fn move_rust_script(
    project: &ProjectRoot,
    source_relative: &Path,
    destination_relative: &Path,
) -> Result<PathBuf, GameProjectError> {
    validate_script_relative_source_path(source_relative)?;
    validate_script_relative_source_path(destination_relative)?;
    let scripts = project.rust_scripts_dir();
    let source = scripts.join(source_relative);
    let destination = scripts.join(destination_relative);
    let source_metadata = component_metadata_path(&source);
    let destination_metadata = component_metadata_path(&destination);
    if !source.is_file() {
        return Err(GameProjectError::MissingSource(source));
    }
    if destination.exists() || destination_metadata.exists() {
        return Err(GameProjectError::PathCollision(destination));
    }
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent).map_err(|source| GameProjectError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::rename(&source, &destination).map_err(|error| GameProjectError::Io {
        path: source.clone(),
        source: error,
    })?;
    let moved_metadata = source_metadata.is_file();
    if moved_metadata
        && let Err(error) = fs::rename(&source_metadata, &destination_metadata)
    {
        let _ = fs::rename(&destination, &source);
        return Err(GameProjectError::Io {
            path: source_metadata,
            source: error,
        });
    }
    if let Err(error) = refresh_game_module_indexes(project) {
        if moved_metadata {
            let _ = fs::rename(&destination_metadata, &source_metadata);
        }
        let _ = fs::rename(&destination, &source);
        let _ = refresh_game_module_indexes(project);
        return Err(error);
    }
    Ok(destination)
}

/// Duplicates one component under a new Rust type and fresh stable ID.
///
/// The source path is relative to `assets/scripts/rust/` and the copy is placed
/// beside it. The new sidecar receives a fresh opaque component ID, so the copy
/// can never reuse the original component identity.
///
/// # Errors
///
/// Returns an error for invalid names, ambiguous source declarations,
/// destination collisions, malformed metadata, or persistence failures.
pub fn duplicate_rust_component(
    project: &ProjectRoot,
    source_relative: &Path,
    new_rust_name: &str,
) -> Result<PathBuf, GameProjectError> {
    validate_script_relative_source_path(source_relative)?;
    validate_rust_type_name(new_rust_name)?;
    validate_project_rust_sources(project)?;
    let scripts = project.rust_scripts_dir();
    let source = scripts.join(source_relative);
    let source_text = fs::read_to_string(&source).map_err(|source_error| GameProjectError::Io {
        path: source.clone(),
        source: source_error,
    })?;
    let declarations = rust_declarations(&source_text)
        .into_iter()
        .filter(|declaration| declaration.kind == RustDeclarationKind::Component)
        .collect::<Vec<_>>();
    let [declaration] = declarations.as_slice() else {
        return Err(GameProjectError::AmbiguousComponentSource(source));
    };
    let destination = source
        .parent()
        .unwrap_or(&scripts)
        .join(format!("{}.rs", to_snake_case(new_rust_name)));
    let destination_metadata = component_metadata_path(&destination);
    if destination.exists() || destination_metadata.exists() {
        return Err(GameProjectError::PathCollision(destination));
    }
    let copied_source = replace_identifier(&source_text, &declaration.rust_name, new_rust_name);
    let component_id = format!(
        "game.c_{}",
        ulid::Ulid::new().to_string().to_ascii_lowercase()
    );
    let metadata = ComponentMetadata::new(component_id).map_err(GameProjectError::Metadata)?;
    replace_file_contents(&destination, &copied_source).map_err(GameProjectError::Persist)?;
    if let Err(error) = write_component_metadata(&destination_metadata, &metadata) {
        let _ = fs::remove_file(&destination);
        return Err(GameProjectError::Metadata(error));
    }
    if let Err(error) = refresh_game_module_indexes(project) {
        let _ = fs::remove_file(&destination_metadata);
        let _ = fs::remove_file(&destination);
        return Err(error);
    }
    Ok(destination)
}

const GENERATED_INDEX_HEADER: &str = "// Automatically generated module index for `assets/scripts/rust/`.\n//\n// `game/src/lib.rs` includes this file at the crate root, so every folder below\n// the Rust script root becomes a Rust module path. Do not edit this file and do\n// not add `mod.rs` files below the Rust script root; the editor regenerates the\n// complete index whenever project Rust sources are added, moved, or removed.\n\n";

const MODULE_INDEX_INCLUDE: &str = "include!(\"project_modules.rs\");";
const GAME_MODULE_EXPORT: &str = "engine::export_game_module!();";
const OBSOLETE_ROOT_DECLARATIONS: [&str; 8] = [
    "mod components;",
    "mod resources;",
    "mod systems;",
    "mod shared;",
    "pub mod components;",
    "pub mod resources;",
    "pub mod systems;",
    "pub mod shared;",
];

/// Rejects existing Cargo-host layouts that are not the current unified tree.
///
/// This function only validates. It never rewrites an old host into the current
/// shape, so initialization cannot silently delete or reinterpret historical
/// scaffolding.
fn validate_current_game_host(project: &ProjectRoot) -> Result<(), GameProjectError> {
    let source_root = project.game_dir().join("src");
    let root_module = source_root.join("lib.rs");
    if root_module.is_file() {
        let contents = fs::read_to_string(&root_module).map_err(|source| GameProjectError::Io {
            path: root_module.clone(),
            source,
        })?;
        let has_index = contents
            .lines()
            .any(|line| line.trim() == MODULE_INDEX_INCLUDE);
        let has_export = contents.lines().any(|line| line.trim() == GAME_MODULE_EXPORT);
        let has_obsolete_declaration = contents
            .lines()
            .any(|line| OBSOLETE_ROOT_DECLARATIONS.contains(&line.trim()));
        if !has_index || !has_export || has_obsolete_declaration {
            return Err(GameProjectError::NonCurrentGameHost(root_module));
        }
    }

    for obsolete in [
        source_root.join("components").join("mod.rs"),
        source_root.join("resources").join("mod.rs"),
        source_root.join("systems").join("mod.rs"),
        source_root.join("shared.rs"),
    ] {
        if obsolete.exists() {
            return Err(GameProjectError::NonCurrentGameHost(obsolete));
        }
    }
    Ok(())
}

fn build_project_module_index(project: &ProjectRoot) -> Result<String, GameProjectError> {
    let mut contents = String::from(GENERATED_INDEX_HEADER);
    write_module_tree(&project.rust_scripts_dir(), 0, &mut contents)?;
    Ok(contents)
}

fn write_module_tree(
    directory: &Path,
    depth: usize,
    output: &mut String,
) -> Result<(), GameProjectError> {
    if !directory.is_dir() {
        return Ok(());
    }
    let mut entries = fs::read_dir(directory)
        .map_err(|source| GameProjectError::Io {
            path: directory.to_path_buf(),
            source,
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|source| GameProjectError::Io {
            path: directory.to_path_buf(),
            source,
        })?;
    entries.sort_by_key(|entry| entry.file_name());
    let indent = "    ".repeat(depth);
    let mut claimed = BTreeMap::<String, PathBuf>::new();
    for entry in entries {
        let path = entry.path();
        let file_name = entry.file_name().to_string_lossy().into_owned();
        if file_name.starts_with('.') {
            continue;
        }
        let file_type = entry.file_type().map_err(|source| GameProjectError::Io {
            path: path.clone(),
            source,
        })?;
        if file_type.is_symlink() {
            return Err(GameProjectError::SymlinkNotSupported(path));
        }
        if file_type.is_dir() {
            let name = rust_module_name(&path)?;
            claim_module_name(&mut claimed, &name, &path)?;
            output.push_str(&format!("{indent}pub mod {name} {{\n"));
            write_module_tree(&path, depth + 1, output)?;
            output.push_str(&format!("{indent}}}\n"));
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            if file_name == "mod.rs" {
                return Err(GameProjectError::ProhibitedModuleFile(path));
            }
            let name = rust_module_name(&path)?;
            claim_module_name(&mut claimed, &name, &path)?;
            let absolute = rust_path_literal(&path);
            output.push_str(&format!(
                "{indent}#[path = \"{absolute}\"]\n{indent}pub mod {name};\n"
            ));
        }
    }
    Ok(())
}

fn claim_module_name(
    claimed: &mut BTreeMap<String, PathBuf>,
    name: &str,
    path: &Path,
) -> Result<(), GameProjectError> {
    if let Some(first) = claimed.insert(name.to_owned(), path.to_path_buf()) {
        return Err(GameProjectError::DuplicateModuleName {
            module: name.to_owned(),
            first,
            second: path.to_path_buf(),
        });
    }
    Ok(())
}

fn rust_path_literal(path: &Path) -> String {
    let path = path.to_string_lossy();
    let path = path.strip_prefix(r"\\?\").unwrap_or(&path);
    path.replace('\\', "/").replace('"', "\\\"")
}

fn rust_module_name(path: &Path) -> Result<String, GameProjectError> {
    let name = if path.is_dir() {
        path.file_name()
    } else {
        path.file_stem()
    }
    .and_then(|name| name.to_str())
    .ok_or_else(|| GameProjectError::InvalidRustModulePath(path.to_path_buf()))?;
    validate_rust_module_name(name)
        .map_err(|_| GameProjectError::InvalidRustModulePath(path.to_path_buf()))?;
    Ok(name.to_owned())
}

/// Rust keywords that cannot name a module even though they are valid ASCII.
const RUST_KEYWORDS: [&str; 51] = [
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "try", "typeof", "unsized", "virtual", "yield",
];

fn validate_rust_module_name(name: &str) -> Result<(), ()> {
    let mut characters = name.chars();
    let valid = characters
        .next()
        .is_some_and(|first| first == '_' || first.is_ascii_alphabetic())
        && characters.all(|character| character == '_' || character.is_ascii_alphanumeric());
    if valid && !RUST_KEYWORDS.contains(&name) {
        Ok(())
    } else {
        Err(())
    }
}

fn validate_project_rust_sources(project: &ProjectRoot) -> Result<(), GameProjectError> {
    let mut rust_sources = Vec::new();
    collect_rust_sources(&project.rust_scripts_dir(), &mut rust_sources)?;
    rust_sources.sort();
    let mut component_ids = BTreeMap::<String, PathBuf>::new();
    let mut registration_ids = BTreeMap::<(RustDeclarationKind, String), PathBuf>::new();
    for source_path in rust_sources {
        let source = fs::read_to_string(&source_path).map_err(|source| GameProjectError::Io {
            path: source_path.clone(),
            source,
        })?;
        let declarations = rust_declarations(&source);
        let components = declarations
            .iter()
            .filter(|declaration| declaration.kind == RustDeclarationKind::Component)
            .count();
        if components > 1 {
            return Err(GameProjectError::AmbiguousComponentSource(source_path));
        }
        if components == 1 {
            let metadata_path = component_metadata_path(&source_path);
            if !metadata_path.exists() {
                return Err(GameProjectError::MissingComponentMetadata(source_path));
            }
            let metadata =
                load_component_metadata(&metadata_path).map_err(GameProjectError::Metadata)?;
            if let Some(previous) =
                component_ids.insert(metadata.component_id.clone(), source_path.clone())
            {
                return Err(GameProjectError::DuplicateComponentId {
                    component_id: metadata.component_id,
                    first: previous,
                    second: source_path,
                });
            }
        }
        for declaration in declarations {
            let (RustDeclarationKind::Resource | RustDeclarationKind::System) = declaration.kind
            else {
                continue;
            };
            let Some(id) = declaration.declared_id else {
                continue;
            };
            if let Some(previous) =
                registration_ids.insert((declaration.kind, id.clone()), source_path.clone())
            {
                return Err(GameProjectError::DuplicateDeclarationId {
                    kind: declaration.kind,
                    id,
                    first: previous,
                    second: source_path,
                });
            }
        }
    }
    Ok(())
}

fn collect_rust_sources(
    directory: &Path,
    output: &mut Vec<PathBuf>,
) -> Result<(), GameProjectError> {
    if !directory.exists() {
        return Ok(());
    }
    let entries = fs::read_dir(directory).map_err(|source| GameProjectError::Io {
        path: directory.to_path_buf(),
        source,
    })?;
    for entry in entries {
        let entry = entry.map_err(|source| GameProjectError::Io {
            path: directory.to_path_buf(),
            source,
        })?;
        let file_type = entry.file_type().map_err(|source| GameProjectError::Io {
            path: entry.path(),
            source,
        })?;
        if file_type.is_symlink() {
            continue;
        }
        if file_type.is_dir() {
            collect_rust_sources(&entry.path(), output)?;
        } else if entry
            .path()
            .extension()
            .is_some_and(|extension| extension == "rs")
        {
            output.push(entry.path());
        }
    }
    Ok(())
}

/// Blanks comment text while preserving byte-for-byte line structure.
///
/// Attribute scanning is line based, so removing comments before the scan keeps
/// a commented-out `#[derive(engine::GameComponent)]` from classifying a plain
/// helper module as a component. Nested block comments end at the first `*/`,
/// and raw string literals are treated as ordinary strings; neither shape
/// appears in the generated sources this scanner classifies.
fn strip_comments(source: &str) -> String {
    let characters = source.chars().collect::<Vec<_>>();
    let mut output = String::with_capacity(source.len());
    let mut index = 0;
    let mut in_line_comment = false;
    let mut in_block_comment = false;
    let mut in_string = false;
    while index < characters.len() {
        let character = characters[index];
        let next = characters.get(index + 1).copied();
        if character == '\n' {
            in_line_comment = false;
            output.push('\n');
            index += 1;
            continue;
        }
        if in_line_comment || in_block_comment {
            if in_block_comment && character == '*' && next == Some('/') {
                in_block_comment = false;
                output.push_str("  ");
                index += 2;
                continue;
            }
            output.push(' ');
            index += 1;
            continue;
        }
        if in_string {
            if character == '\\' {
                output.push(' ');
                index += 1;
                match characters.get(index) {
                    Some('\n') => output.push('\n'),
                    Some(_) => output.push(' '),
                    None => break,
                }
                index += 1;
                continue;
            }
            if character == '"' {
                in_string = false;
            }
            output.push(character);
            index += 1;
            continue;
        }
        if character == '/' && matches!(next, Some('/') | Some('*')) {
            if next == Some('/') {
                in_line_comment = true;
            } else {
                in_block_comment = true;
            }
            output.push_str("  ");
            index += 2;
            continue;
        }
        if character == '"' {
            in_string = true;
        }
        output.push(character);
        index += 1;
    }
    output
}

struct CollectedAttribute {
    text: String,
    end_line: usize,
    trailing: String,
}

fn collect_attribute(lines: &[&str], start: usize) -> CollectedAttribute {
    let mut text = lines.get(start).copied().unwrap_or_default().to_owned();
    let mut end_line = start;
    while !text.contains(']') && end_line + 1 < lines.len() {
        end_line += 1;
        text.push(' ');
        text.push_str(lines[end_line]);
    }
    let trailing = lines
        .get(end_line)
        .and_then(|line| line.rsplit_once(']'))
        .map(|(_, tail)| tail.to_owned())
        .unwrap_or_default();
    CollectedAttribute {
        text,
        end_line,
        trailing,
    }
}

fn attribute_declaration_kind(attribute: &str) -> Option<RustDeclarationKind> {
    let body = attribute.trim_start().strip_prefix("#[")?;
    let name_end = body.find(['(', ']', '=']).unwrap_or(body.len());
    let name = body[..name_end].trim();
    let name = name.rsplit("::").next().unwrap_or(name);
    match name {
        "game_component" => return Some(RustDeclarationKind::Component),
        "game_resource" => return Some(RustDeclarationKind::Resource),
        "game_system" => return Some(RustDeclarationKind::System),
        "derive" => {}
        _ => return None,
    }
    let arguments = body[name_end..]
        .trim_start()
        .strip_prefix('(')?
        .split(')')
        .next()?;
    for argument in arguments.split(',') {
        let trait_name = argument.trim().rsplit("::").next().unwrap_or("").trim();
        match trait_name {
            "GameComponent" => return Some(RustDeclarationKind::Component),
            "GameResource" => return Some(RustDeclarationKind::Resource),
            _ => {}
        }
    }
    None
}

fn attribute_string_argument(attribute: &str, key: &str) -> Option<String> {
    let mut rest = attribute;
    while let Some(position) = rest.find(key) {
        let before_is_boundary = rest[..position]
            .chars()
            .next_back()
            .is_none_or(|character| !character.is_ascii_alphanumeric() && character != '_');
        let after = &rest[position + key.len()..];
        let value = after.trim_start();
        if before_is_boundary
            && let Some(value) = value.strip_prefix('=')
            && let Some(value) = value.trim_start().strip_prefix('"')
        {
            return value.split('"').next().map(str::to_owned);
        }
        rest = after;
    }
    None
}

fn next_declaration(
    lines: &[&str],
    attribute: &CollectedAttribute,
    kind: RustDeclarationKind,
) -> Option<(usize, String)> {
    if let Some(name) = declaration_name(&attribute.trailing, kind) {
        return Some((attribute.end_line + 1, name));
    }
    for (line_index, line) in lines.iter().enumerate().skip(attribute.end_line + 1) {
        let trimmed = line.trim();
        if trimmed.starts_with("#[") || trimmed.is_empty() {
            continue;
        }
        return declaration_name(trimmed, kind).map(|name| (line_index + 1, name));
    }
    None
}

fn declaration_name(declaration: &str, kind: RustDeclarationKind) -> Option<String> {
    let keywords: &[&str] = match kind {
        RustDeclarationKind::Component | RustDeclarationKind::Resource => &["struct", "enum"],
        RustDeclarationKind::System => &["fn"],
    };
    let tokens = declaration
        .split(|character: char| {
            character.is_whitespace()
                || character == '{'
                || character == '('
                || character == '<'
                || character == ';'
        })
        .filter(|token| !token.is_empty())
        .collect::<Vec<_>>();
    let keyword = tokens.iter().position(|token| keywords.contains(token))?;
    tokens.get(keyword + 1).map(|name| (*name).to_owned())
}

fn replace_identifier(source: &str, old: &str, new: &str) -> String {
    let mut output = String::with_capacity(source.len() + new.len().saturating_sub(old.len()));
    let mut offset = 0;
    while let Some(relative) = source[offset..].find(old) {
        let start = offset + relative;
        let end = start + old.len();
        let before_is_boundary = start == 0
            || !source.as_bytes()[start - 1].is_ascii_alphanumeric()
                && source.as_bytes()[start - 1] != b'_';
        let after_is_boundary = source
            .as_bytes()
            .get(end)
            .is_none_or(|byte| !byte.is_ascii_alphanumeric() && *byte != b'_');
        output.push_str(&source[offset..start]);
        if before_is_boundary && after_is_boundary {
            output.push_str(new);
        } else {
            output.push_str(old);
        }
        offset = end;
    }
    output.push_str(&source[offset..]);
    output
}

fn validate_script_relative_source_path(path: &Path) -> Result<(), GameProjectError> {
    let is_safe = !path.as_os_str().is_empty()
        && !path.is_absolute()
        && path.extension().is_some_and(|extension| extension == "rs")
        && path.file_name().is_some_and(|name| name != "mod.rs")
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_)));
    if is_safe {
        Ok(())
    } else {
        Err(GameProjectError::InvalidScriptPath(path.to_path_buf()))
    }
}

fn validate_script_folder(path: &Path) -> Result<(), GameProjectError> {
    let is_safe = !path.is_absolute()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_)));
    if is_safe || path.as_os_str().is_empty() {
        Ok(())
    } else {
        Err(GameProjectError::InvalidScriptFolder(path.to_path_buf()))
    }
}

fn write_if_missing(path: &Path, contents: &str) -> Result<(), GameProjectError> {
    if path.exists() {
        return Ok(());
    }
    replace_file_contents(path, contents).map_err(GameProjectError::Persist)
}

/// Keeps project-local game crates out of an unrelated ancestor workspace.
///
/// A game project may live anywhere on disk, including inside the engine
/// repository during examples and tests. Cargo otherwise assumes the nearest
/// ancestor workspace owns the crate and rejects it when it is not listed as a
/// member. Appending an empty workspace preserves every existing package and
/// dependency setting while making the game crate an explicit workspace root.
fn ensure_standalone_workspace(manifest: &Path) -> Result<(), GameProjectError> {
    let contents = fs::read_to_string(manifest).map_err(|source| GameProjectError::Io {
        path: manifest.to_path_buf(),
        source,
    })?;
    let has_workspace = contents.lines().any(|line| {
        let line = line.trim();
        line == "[workspace]" || line.starts_with("[workspace.")
    });
    if has_workspace {
        return Ok(());
    }

    let separator = if contents.ends_with('\n') {
        "\n"
    } else {
        "\n\n"
    };
    let migrated = format!("{contents}{separator}[workspace]\n");
    replace_file_contents(manifest, &migrated).map_err(GameProjectError::Persist)
}

fn validate_rust_type_name(name: &str) -> Result<(), GameProjectError> {
    let mut characters = name.chars();
    let Some(first) = characters.next() else {
        return Err(GameProjectError::InvalidName(
            "name must not be empty".to_owned(),
        ));
    };
    if !first.is_ascii_uppercase() {
        return Err(GameProjectError::InvalidName(
            "name must start with an uppercase ASCII letter".to_owned(),
        ));
    }
    if !characters.all(|character| character.is_ascii_alphanumeric()) {
        return Err(GameProjectError::InvalidName(
            "name may contain only ASCII letters and digits".to_owned(),
        ));
    }
    Ok(())
}

fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_uppercase() {
            if index > 0 {
                result.push('_');
            }
            result.push(character.to_ascii_lowercase());
        } else {
            result.push(character);
        }
    }
    result
}

/// Errors returned by project-local Rust initialization and generation.
#[derive(Debug)]
pub enum GameProjectError {
    /// The requested Rust type name is invalid.
    InvalidName(String),
    /// The requested destination file already exists.
    DuplicateName(String),
    /// A script operation used an unsafe or unsupported relative path.
    InvalidScriptPath(PathBuf),
    /// A requested creation folder escaped the Rust script root.
    InvalidScriptFolder(PathBuf),
    /// A source or folder name cannot be represented as a Rust module.
    InvalidRustModulePath(PathBuf),
    /// A `mod.rs` was found below the Rust script root.
    ProhibitedModuleFile(PathBuf),
    /// An existing Cargo host or bridge does not use the current unified layout.
    NonCurrentGameHost(PathBuf),
    /// Two entries in one folder generate the same Rust module name.
    DuplicateModuleName {
        /// Module name claimed twice.
        module: String,
        /// First entry claiming the name.
        first: PathBuf,
        /// Second entry claiming the name.
        second: PathBuf,
    },
    /// A symlink was found below the Rust script root.
    SymlinkNotSupported(PathBuf),
    /// The requested source does not exist.
    MissingSource(PathBuf),
    /// A component source has no usable current sidecar metadata.
    MissingComponentMetadata(PathBuf),
    /// A component source contains multiple component declarations.
    AmbiguousComponentSource(PathBuf),
    /// A destination source or sidecar already exists.
    PathCollision(PathBuf),
    /// Two sidecars resolve to the same stable component ID.
    DuplicateComponentId {
        /// Duplicated stable ID.
        component_id: String,
        /// First source carrying the ID.
        first: PathBuf,
        /// Second source carrying the ID.
        second: PathBuf,
    },
    /// Two sources declare the same resource or system registration ID.
    DuplicateDeclarationId {
        /// Declaration kind carrying the duplicated ID.
        kind: RustDeclarationKind,
        /// Duplicated registration ID.
        id: String,
        /// First source carrying the ID.
        first: PathBuf,
        /// Second source carrying the ID.
        second: PathBuf,
    },
    /// Component sidecar validation or persistence failed.
    Metadata(ComponentMetadataError),
    /// A filesystem operation failed.
    Io {
        /// Path being accessed.
        path: PathBuf,
        /// Underlying error.
        source: io::Error,
    },
    /// Atomic file replacement failed.
    Persist(PersistError),
}

impl fmt::Display for GameProjectError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidName(reason) => write!(formatter, "invalid Rust script name: {reason}"),
            Self::DuplicateName(name) => write!(formatter, "Rust script `{name}` already exists"),
            Self::InvalidScriptPath(path) => write!(
                formatter,
                "script path `{}` must be a relative `.rs` path below assets/scripts/rust",
                path.display()
            ),
            Self::InvalidScriptFolder(path) => write!(
                formatter,
                "Rust script folder `{}` must stay below assets/scripts/rust and use Rust module names",
                path.display()
            ),
            Self::InvalidRustModulePath(path) => write!(
                formatter,
                "Rust source path `{}` is not a valid Rust module name",
                path.display()
            ),
            Self::ProhibitedModuleFile(path) => write!(
                formatter,
                "{} is a `mod.rs`; the module index below assets/scripts/rust is generated, so rename this file to an ordinary module name",
                path.display()
            ),
            Self::NonCurrentGameHost(path) => write!(
                formatter,
                "{} is not part of the current unified project Rust host; restore the current `game/src/lib.rs` and remove obsolete host bridge files instead of relying on automatic migration",
                path.display()
            ),
            Self::DuplicateModuleName {
                module,
                first,
                second,
            } => write!(
                formatter,
                "Rust module name `{module}` is generated twice by {} and {}",
                first.display(),
                second.display()
            ),
            Self::SymlinkNotSupported(path) => write!(
                formatter,
                "Rust script root rejected symlink `{}`",
                path.display()
            ),
            Self::MissingSource(path) => {
                write!(formatter, "Rust source {} does not exist", path.display())
            }
            Self::MissingComponentMetadata(path) => write!(
                formatter,
                "component source {} has no sidecar metadata; restore its `.rs.meta.json` file",
                path.display()
            ),
            Self::AmbiguousComponentSource(path) => write!(
                formatter,
                "component source {} must contain exactly one GameComponent declaration",
                path.display()
            ),
            Self::PathCollision(path) => {
                write!(formatter, "destination {} already exists", path.display())
            }
            Self::DuplicateComponentId {
                component_id,
                first,
                second,
            } => write!(
                formatter,
                "component ID `{component_id}` is duplicated by {} and {}",
                first.display(),
                second.display()
            ),
            Self::DuplicateDeclarationId {
                kind,
                id,
                first,
                second,
            } => write!(
                formatter,
                "{} ID `{id}` is duplicated by {} and {}",
                kind.label(),
                first.display(),
                second.display()
            ),
            Self::Metadata(source) => source.fmt(formatter),
            Self::Io { path, source } => {
                write!(formatter, "could not access {}: {source}", path.display())
            }
            Self::Persist(source) => source.fmt(formatter),
        }
    }
}

impl std::error::Error for GameProjectError {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ProjectConfig, PROJECT_SCHEMA_VERSION};
    use tempfile::tempdir;

    fn project() -> (tempfile::TempDir, ProjectRoot) {
        let directory = tempdir().unwrap();
        let project = ProjectRoot::create(
            directory.path(),
            ProjectConfig {
                name: "test".to_owned(),
                schema_version: PROJECT_SCHEMA_VERSION,
            },
        )
        .unwrap();
        (directory, project)
    }

    fn module_index(project: &ProjectRoot) -> String {
        fs::read_to_string(project.game_module_index_path()).unwrap()
    }

    #[test]
    fn initialization_creates_recommended_folders_and_is_idempotent() {
        let (_directory, project) = project();
        initialize_game_project(&project).unwrap();
        initialize_game_project(&project).unwrap();
        let manifest = fs::read_to_string(project.game_dir().join("Cargo.toml")).unwrap();
        assert_eq!(manifest.matches("[workspace]").count(), 1);
        for folder in RECOMMENDED_RUST_SCRIPT_FOLDERS {
            assert!(project.rust_scripts_dir().join(folder).is_dir());
        }
        assert!(project.game_module_index_path().is_file());
        assert!(project.path().join(".vscode/settings.json").is_file());
        let root = fs::read_to_string(project.game_dir().join("src/lib.rs")).unwrap();
        assert_eq!(root.matches(MODULE_INDEX_INCLUDE).count(), 1);
        assert_eq!(root.matches(GAME_MODULE_EXPORT).count(), 1);
    }

    #[test]
    fn initialization_preserves_existing_manifest_settings() {
        let (_directory, project) = project();
        let manifest = project.game_dir().join("Cargo.toml");
        fs::create_dir_all(project.game_dir()).unwrap();
        fs::write(
            &manifest,
            "[package]\nname = \"custom-game\"\nversion = \"9.9.9\"\n",
        )
        .unwrap();

        initialize_game_project(&project).unwrap();

        let updated = fs::read_to_string(manifest).unwrap();
        assert!(updated.contains("name = \"custom-game\""));
        assert!(updated.contains("version = \"9.9.9\""));
        assert_eq!(updated.matches("[workspace]").count(), 1);
    }

    #[test]
    fn legacy_per_category_host_is_rejected_without_mutation() {
        let (_directory, project) = project();
        let source_root = project.game_dir().join("src");
        fs::create_dir_all(source_root.join("components")).unwrap();
        let root_contents = "//! Legacy host.\nmod components;\n\nengine::export_game_module!();\n";
        let bridge_contents = "//! Automatically generated bridge to user-authored sources in assets.\n";
        fs::write(source_root.join("lib.rs"), root_contents).unwrap();
        fs::write(source_root.join("components/mod.rs"), bridge_contents).unwrap();

        assert!(matches!(
            initialize_game_project(&project),
            Err(GameProjectError::NonCurrentGameHost(_))
        ));
        assert_eq!(
            fs::read_to_string(source_root.join("lib.rs")).unwrap(),
            root_contents
        );
        assert_eq!(
            fs::read_to_string(source_root.join("components/mod.rs")).unwrap(),
            bridge_contents
        );
        assert!(!project.game_module_index_path().exists());
    }

    #[test]
    fn hand_written_module_file_below_the_script_root_is_rejected() {
        let (_directory, project) = project();
        initialize_game_project(&project).unwrap();
        fs::write(
            project.rust_shared_dir().join("mod.rs"),
            "pub fn helper() -> bool { true }\n",
        )
        .unwrap();

        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::ProhibitedModuleFile(_))
        ));
        assert!(matches!(
            initialize_game_project(&project),
            Err(GameProjectError::ProhibitedModuleFile(_))
        ));
    }

    #[test]
    fn component_generation_writes_sidecar_and_rejects_a_second_file_in_one_folder() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let source = fs::read_to_string(&path).unwrap();
        assert!(source.contains("game_component(display_name = \"Health\")"));
        assert!(!source.contains("id ="));
        let metadata = load_component_metadata(&component_metadata_path(&path)).unwrap();
        assert!(metadata.component_id.starts_with("game.c_"));
        assert!(matches!(
            create_rust_script_in(
                &project,
                RustScriptKind::System,
                Path::new("components"),
                "Health",
                RustScriptSchedule::Update
            ),
            Err(GameProjectError::DuplicateName(_))
        ));
    }

    #[test]
    fn one_file_stem_may_exist_in_several_folders() {
        let (_directory, project) = project();
        let player = create_rust_script_in(
            &project,
            RustScriptKind::Component,
            Path::new("player"),
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let enemy = create_rust_script_in(
            &project,
            RustScriptKind::Component,
            Path::new("enemy"),
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();

        assert_eq!(player, project.rust_scripts_dir().join("player/health.rs"));
        assert_eq!(enemy, project.rust_scripts_dir().join("enemy/health.rs"));
        let index = module_index(&project);
        assert!(index.contains("pub mod player {"));
        assert!(index.contains("pub mod enemy {"));
        assert_eq!(index.matches("pub mod health;").count(), 2);
    }

    #[test]
    fn colliding_module_names_in_one_folder_are_rejected() {
        let (_directory, project) = project();
        initialize_game_project(&project).unwrap();
        fs::write(
            project.rust_scripts_dir().join("shared/math.rs"),
            "pub fn a() {}\n",
        )
        .unwrap();
        fs::create_dir_all(project.rust_scripts_dir().join("shared/math")).unwrap();
        fs::write(
            project.rust_scripts_dir().join("shared/math/vector.rs"),
            "pub fn b() {}\n",
        )
        .unwrap();

        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::DuplicateModuleName { .. })
        ));
    }

    #[test]
    fn invalid_folder_and_file_names_are_rejected_by_index_generation() {
        let (_directory, project) = project();
        initialize_game_project(&project).unwrap();
        let invalid = project.rust_scripts_dir().join("player-movement");
        fs::create_dir_all(&invalid).unwrap();

        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::InvalidRustModulePath(_))
        ));

        fs::remove_dir_all(&invalid).unwrap();
        fs::create_dir_all(project.rust_scripts_dir().join("type")).unwrap();
        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::InvalidRustModulePath(_))
        ));
    }

    #[test]
    fn nested_folders_become_nested_rust_module_paths() {
        let (_directory, project) = project();
        let path = create_rust_script_in(
            &project,
            RustScriptKind::Component,
            Path::new("player/movement"),
            "MoveRule",
            RustScriptSchedule::Update,
        )
        .unwrap();

        assert_eq!(
            path,
            project
                .rust_scripts_dir()
                .join("player/movement/move_rule.rs")
        );
        let index = module_index(&project);
        assert!(index.contains("pub mod player {"));
        assert!(index.contains("    pub mod movement {"));
        assert!(index.contains("pub mod move_rule;"));
    }

    #[test]
    fn ordinary_modules_outside_shared_are_compiled() {
        let (_directory, project) = project();
        initialize_game_project(&project).unwrap();
        let directory = project.rust_scripts_dir().join("common");
        fs::create_dir_all(&directory).unwrap();
        fs::write(
            directory.join("math.rs"),
            "/// Ordinary helper.\npub fn calculate_damage() -> f32 {\n    10.0\n}\n",
        )
        .unwrap();

        refresh_game_module_indexes(&project).unwrap();

        let index = module_index(&project);
        assert!(index.contains("pub mod common {"));
        assert!(index.contains("pub mod math;"));
    }

    #[test]
    fn repeated_initialization_preserves_component_id() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let metadata_path = component_metadata_path(&path);
        let original = load_component_metadata(&metadata_path).unwrap();

        initialize_game_project(&project).unwrap();

        assert_eq!(load_component_metadata(&metadata_path).unwrap(), original);
    }

    #[test]
    fn rust_type_rename_preserves_sidecar_component_id() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let metadata_path = component_metadata_path(&path);
        let original = load_component_metadata(&metadata_path).unwrap();
        let source = fs::read_to_string(&path)
            .unwrap()
            .replace("Health", "HitPoints");
        fs::write(&path, source).unwrap();

        refresh_game_module_indexes(&project).unwrap();

        assert_eq!(load_component_metadata(&metadata_path).unwrap(), original);
    }

    #[test]
    fn script_move_across_folders_carries_the_sidecar_without_changing_the_id() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let original = load_component_metadata(&component_metadata_path(&path)).unwrap();

        let moved = move_rust_script(
            &project,
            Path::new("components/health.rs"),
            Path::new("player/combat/hit_points.rs"),
        )
        .unwrap();

        assert!(!path.exists());
        assert_eq!(
            load_component_metadata(&component_metadata_path(&moved)).unwrap(),
            original
        );
        let index = module_index(&project);
        assert!(index.contains("pub mod player {"));
        assert!(index.contains("hit_points.rs"));
        assert!(!index.contains("components/health.rs"));
    }

    #[test]
    fn ordinary_module_moves_without_a_sidecar() {
        let (_directory, project) = project();
        create_rust_script(
            &project,
            RustScriptKind::SharedModule,
            "Math",
            RustScriptSchedule::Update,
        )
        .unwrap();

        let moved = move_rust_script(
            &project,
            Path::new("shared/math.rs"),
            Path::new("common/math.rs"),
        )
        .unwrap();

        assert!(moved.is_file());
        assert!(module_index(&project).contains("common/math.rs"));
    }

    #[test]
    fn component_duplicate_gets_a_fresh_id_and_new_rust_type() {
        let (_directory, project) = project();
        let original_path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let original = load_component_metadata(&component_metadata_path(&original_path)).unwrap();

        let duplicate =
            duplicate_rust_component(&project, Path::new("components/health.rs"), "EnemyHealth")
                .unwrap();
        let copied = load_component_metadata(&component_metadata_path(&duplicate)).unwrap();

        assert_ne!(original.component_id, copied.component_id);
        let source = fs::read_to_string(duplicate).unwrap();
        assert!(source.contains("pub struct EnemyHealth"));
        assert!(!source.contains("id ="));
    }

    #[test]
    fn missing_or_corrupt_sidecar_never_generates_a_replacement_id() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let metadata_path = component_metadata_path(&path);
        fs::remove_file(&metadata_path).unwrap();
        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::MissingComponentMetadata(_))
        ));
        assert!(!metadata_path.exists());

        fs::write(&metadata_path, "{").unwrap();
        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::Metadata(
                ComponentMetadataError::Json { .. }
            ))
        ));
    }

    #[test]
    fn duplicate_sidecar_ids_block_module_index_refresh() {
        let (_directory, project) = project();
        let first = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let second = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Armor",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let first_metadata = fs::read_to_string(component_metadata_path(&first)).unwrap();
        fs::write(component_metadata_path(&second), first_metadata).unwrap();

        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::DuplicateComponentId { .. })
        ));
    }

    #[test]
    fn duplicate_resource_and_system_ids_block_module_index_refresh() {
        let (_directory, project) = project();
        create_rust_script_in(
            &project,
            RustScriptKind::Resource,
            Path::new("gameplay"),
            "MissionState",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let copy = project.rust_scripts_dir().join("hud/mission_state.rs");
        fs::create_dir_all(copy.parent().unwrap()).unwrap();
        fs::write(
            &copy,
            "#[derive(Default, engine::GameResource)]\n#[game_resource(id = \"game.mission_state\", display_name = \"Copy\")]\npub struct MissionStateCopy {\n    pub enabled: bool,\n}\n",
        )
        .unwrap();

        assert!(matches!(
            refresh_game_module_indexes(&project),
            Err(GameProjectError::DuplicateDeclarationId {
                kind: RustDeclarationKind::Resource,
                ..
            })
        ));
    }

    #[test]
    fn scene_and_prefab_roundtrips_preserve_sidecar_component_id() {
        let (_directory, project) = project();
        let component_path = create_rust_script(
            &project,
            RustScriptKind::Component,
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let component_id = load_component_metadata(&component_metadata_path(&component_path))
            .unwrap()
            .component_id;
        let component_type = crate::ComponentTypeId::new(component_id.clone());
        let entity_id = crate::EntityId::generate();
        let mut scene = crate::AuthoringScene::new();
        let mut transaction = crate::Transaction::begin(&scene);
        transaction.apply(crate::AuthoringCommand::CreateEntity {
            id: entity_id.clone(),
            name: "player".to_owned(),
            parent: None,
        });
        transaction.apply(crate::AuthoringCommand::AddComponent {
            entity: entity_id.clone(),
            component_type: component_type.clone(),
            value: crate::Value::Object(Default::default()),
        });
        transaction.commit(&mut scene).unwrap();

        // The stable ID must survive a free-form relocation as well.
        move_rust_script(
            &project,
            Path::new("components/health.rs"),
            Path::new("player/health.rs"),
        )
        .unwrap();

        let scene_json = scene.to_canonical_json().unwrap();
        let reopened_scene = crate::load_scene_from_json(&scene_json).unwrap();
        assert!(reopened_scene
            .entity(&entity_id)
            .unwrap()
            .components
            .contains_key(&component_type));

        let prefab = crate::PrefabAsset::from_selection(reopened_scene.entities()).unwrap();
        let prefab_json = prefab.to_json().unwrap();
        let reopened_prefab = crate::PrefabAsset::from_json(&prefab_json).unwrap();
        assert!(reopened_prefab
            .entities
            .values()
            .any(|entity| entity.components.contains_key(&component_type)));
        assert!(scene_json.contains(&component_id));
        assert!(prefab_json.contains(&component_id));
        assert_eq!(
            load_component_metadata(&component_metadata_path(
                &project.rust_scripts_dir().join("player/health.rs")
            ))
            .unwrap()
            .component_id,
            component_id
        );
    }

    #[test]
    fn system_generation_uses_typed_parameter_driven_access() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::System,
            "PlayerCombat",
            RustScriptSchedule::FixedUpdate,
        )
        .unwrap();
        let source = fs::read_to_string(path).unwrap();

        assert!(source.contains("use engine::prelude::*;"));
        assert!(source.contains("fn player_combat() {}"));
        assert!(!source.contains("GameSystemAccess"));
        assert!(!source.contains("GameInvocation"));
        assert!(!source.contains("GameWorld"));
    }

    #[test]
    fn resource_generation_uses_host_owned_runtime_schema() {
        let (_directory, project) = project();
        let path = create_rust_script(
            &project,
            RustScriptKind::Resource,
            "MissionState",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let source = fs::read_to_string(path).unwrap();

        assert!(source.contains("engine::GameResource"));
        assert!(source.contains("game_resource(id = \"game.mission_state\""));
        assert!(source.contains("not\n/// written to scenes or saves"));
        assert!(module_index(&project).contains("pub mod mission_state;"));
    }

    #[test]
    fn scripts_are_created_in_assets_and_game_contains_only_the_generated_index() {
        let (_directory, project) = project();
        let component = create_rust_script_in(
            &project,
            RustScriptKind::Component,
            Path::new("enemies"),
            "Health",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let shared = create_rust_script(
            &project,
            RustScriptKind::SharedModule,
            "MathHelpers",
            RustScriptSchedule::Update,
        )
        .unwrap();
        let rhai = create_rhai_script_in(&project, Path::new("ai"), "enemy").unwrap();

        assert_eq!(
            component,
            project.rust_scripts_dir().join("enemies/health.rs")
        );
        assert_eq!(shared, project.rust_shared_dir().join("math_helpers.rs"));
        assert_eq!(rhai, project.rhai_scripts_dir().join("ai/enemy.rhai"));
        assert!(!project.game_dir().join("src/components").exists());
        let index = module_index(&project);
        assert!(index.contains("assets/scripts/rust/enemies/health.rs"));
        assert!(index.contains("pub mod math_helpers;"));
    }

    #[test]
    fn initialization_preserves_a_current_custom_root() {
        let (_directory, project) = project();
        let source_root = project.game_dir().join("src");
        fs::create_dir_all(&source_root).unwrap();
        let current_root = "#![allow(dead_code)]\nmod custom;\ninclude!(\"project_modules.rs\");\nengine::export_game_module!();\n";
        fs::write(source_root.join("lib.rs"), current_root).unwrap();

        initialize_game_project(&project).unwrap();

        assert_eq!(
            fs::read_to_string(source_root.join("lib.rs")).unwrap(),
            current_root
        );
        assert!(project.game_module_index_path().is_file());
    }

    #[test]
    fn non_current_custom_root_is_rejected() {
        let (_directory, project) = project();
        let source_root = project.game_dir().join("src");
        fs::create_dir_all(&source_root).unwrap();
        fs::write(
            source_root.join("lib.rs"),
            "#![allow(dead_code)]\nmod custom;\n",
        )
        .unwrap();

        assert!(matches!(
            initialize_game_project(&project),
            Err(GameProjectError::NonCurrentGameHost(_))
        ));
        assert!(!project.game_module_index_path().exists());
    }

    #[test]
    fn invalid_names_are_rejected_before_writing() {
        let (_directory, project) = project();
        assert!(matches!(
            create_rust_script(
                &project,
                RustScriptKind::Component,
                "bad name",
                RustScriptSchedule::Update
            ),
            Err(GameProjectError::InvalidName(_))
        ));
        assert!(matches!(
            create_rust_script_in(
                &project,
                RustScriptKind::Component,
                Path::new("player-movement"),
                "Health",
                RustScriptSchedule::Update
            ),
            Err(GameProjectError::InvalidScriptFolder(_))
        ));
    }

    #[test]
    fn declarations_are_detected_from_source_attributes_not_folders() {
        let component = rust_declarations(
            "//! Doc.\n#[derive(\n    Debug,\n    engine::GameComponent,\n)]\n#[game_component(display_name = \"Health\")]\npub struct Health {\n    pub enabled: bool,\n}\n",
        );
        assert_eq!(component.len(), 1);
        assert_eq!(component[0].kind, RustDeclarationKind::Component);
        assert_eq!(component[0].rust_name, "Health");

        let resource = rust_declarations(
            "#[derive(Default, engine::GameResource)]\n#[game_resource(id = \"game.mission\", display_name = \"Mission\")]\npub struct MissionState;\n",
        );
        assert_eq!(resource[0].kind, RustDeclarationKind::Resource);
        assert_eq!(resource[0].declared_id.as_deref(), Some("game.mission"));

        let system = rust_declarations(
            "#[engine::game_system(\n    id = \"game.tick\",\n    schedule = \"update\"\n)]\nfn tick() {}\n",
        );
        assert_eq!(system[0].kind, RustDeclarationKind::System);
        assert_eq!(system[0].rust_name, "tick");
        assert_eq!(system[0].declared_id.as_deref(), Some("game.tick"));
    }

    #[test]
    fn commented_out_declarations_are_not_detected() {
        let source = "//! `#[derive(engine::GameComponent)]` is documented here.\n\n// #[derive(engine::GameComponent)]\n// pub struct Ghost;\n\n/* #[game_system(id = \"game.ghost\")]\nfn ghost() {}\n*/\n\n/// Ordinary helper.\npub fn calculate_damage() -> f32 {\n    10.0\n}\n";
        assert!(rust_declarations(source).is_empty());
    }

    #[test]
    fn plain_module_sources_declare_nothing() {
        assert!(rust_declarations("pub fn calculate_damage() -> f32 {\n    10.0\n}\n").is_empty());
    }
}
