// Automatically generated module index for `assets/scripts/rust/`.
//
// `game/src/lib.rs` includes this file at the crate root, so every folder below
// the Rust script root becomes a Rust module path. Do not edit this file and do
// not add `mod.rs` files below the Rust script root; the editor regenerates the
// complete index whenever project Rust sources are added, moved, or removed.

pub mod components {
}
pub mod resources {
}
pub mod shared {
}
pub mod systems {
}
