//! Unity-style typed parameter authoring for Animation Graph transitions.
//!
//! Parameters are declared on the graph's Entry node. State-transition
//! conditions are generated by typed Inspector controls, so authors never enter
//! persisted condition expressions manually.

use super::*;
use std::collections::BTreeMap;

const PARAMETERS_PROPERTY: &str = "parameters";
const PARAMETER_UI_STATE_ID: &str = "animation_graph_parameter_ui_state";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum GraphParameterKind {
    #[default]
    Bool,
    Float,
    Trigger,
}

impl GraphParameterKind {
    const ALL: [Self; 3] = [Self::Bool, Self::Float, Self::Trigger];

    const fn label(self) -> &'static str {
        match self {
            Self::Bool => "Bool",
            Self::Float => "Float",
            Self::Trigger => "Trigger",
        }
    }

    const fn persisted_name(self) -> &'static str {
        match self {
            Self::Bool => "bool",
            Self::Float => "float",
            Self::Trigger => "trigger",
        }
    }

    fn from_persisted_name(value: &str) -> Option<Self> {
        match value {
            "bool" => Some(Self::Bool),
            "float" => Some(Self::Float),
            "trigger" => Some(Self::Trigger),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct GraphParameter {
    name: String,
    kind: GraphParameterKind,
}

#[derive(Debug, Clone, Default)]
struct GraphParameterUiState {
    new_name: String,
    new_kind: GraphParameterKind,
    rename_buffers: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FloatComparison {
    Less,
    LessOrEqual,
    Greater,
    GreaterOrEqual,
    Equal,
    NotEqual,
}

impl FloatComparison {
    const ALL: [Self; 6] = [
        Self::Less,
        Self::LessOrEqual,
        Self::Greater,
        Self::GreaterOrEqual,
        Self::Equal,
        Self::NotEqual,
    ];

    const fn token(self) -> &'static str {
        match self {
            Self::Less => "<",
            Self::LessOrEqual => "<=",
            Self::Greater => ">",
            Self::GreaterOrEqual => ">=",
            Self::Equal => "==",
            Self::NotEqual => "!=",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
enum TypedTransitionCondition {
    Always,
    Bool {
        parameter: String,
        expected: bool,
    },
    Float {
        parameter: String,
        comparison: FloatComparison,
        threshold: f64,
    },
    Trigger {
        parameter: String,
    },
    Invalid(String),
}

impl TypedTransitionCondition {
    fn parameter(&self) -> Option<&str> {
        match self {
            Self::Bool { parameter, .. }
            | Self::Float { parameter, .. }
            | Self::Trigger { parameter } => Some(parameter),
            Self::Always | Self::Invalid(_) => None,
        }
    }

    const fn kind(&self) -> Option<GraphParameterKind> {
        match self {
            Self::Bool { .. } => Some(GraphParameterKind::Bool),
            Self::Float { .. } => Some(GraphParameterKind::Float),
            Self::Trigger { .. } => Some(GraphParameterKind::Trigger),
            Self::Always | Self::Invalid(_) => None,
        }
    }

    fn rename_parameter(&mut self, old: &str, new: &str) {
        if self.parameter() != Some(old) {
            return;
        }
        match self {
            Self::Bool { parameter, .. }
            | Self::Float { parameter, .. }
            | Self::Trigger { parameter } => *parameter = new.to_owned(),
            Self::Always | Self::Invalid(_) => {}
        }
    }

    fn encode(&self) -> String {
        match self {
            Self::Always => String::new(),
            Self::Bool {
                parameter,
                expected,
            } => format!("{parameter} == {expected}"),
            Self::Float {
                parameter,
                comparison,
                threshold,
            } => format!("{parameter} {} {threshold}", comparison.token()),
            Self::Trigger { parameter } => format!("trigger {parameter}"),
            Self::Invalid(raw) => raw.clone(),
        }
    }
}

#[derive(Debug, Clone)]
enum ParameterAction {
    Rename { old: String, new: String },
    ChangeKind { name: String, kind: GraphParameterKind },
    Delete(String),
}

impl EditorApp {
    /// Draws graph-owned parameter declarations and structured transition controls.
    pub(super) fn show_animation_graph_parameter_inspector(&mut self, ui: &mut egui::Ui) {
        let state_id = egui::Id::new(PARAMETER_UI_STATE_ID);
        let mut ui_state = ui
            .ctx()
            .data_mut(|data| data.remove_temp::<GraphParameterUiState>(state_id))
            .unwrap_or_default();
        let mut parameters = animation_graph_parameters(self.session.graph());

        ui.heading("Animation Parameters");
        ui.small(
            "Declare Bool, Float, and Trigger parameters here. Transitions can only use declared parameters.",
        );
        self.show_animation_parameter_creation(ui, &parameters, &mut ui_state);
        ui.separator();

        if let Some(action) = show_animation_parameter_rows(ui, &parameters, &mut ui_state) {
            if let Err(error) =
                self.apply_animation_parameter_action(action, &mut parameters, &mut ui_state)
            {
                self.report_error("editor.animation_parameter_update_failed", error);
            }
            parameters = animation_graph_parameters(self.session.graph());
        }

        ui.separator();
        let selected_edge = self.session.selected_edge().cloned();
        let selected_is_state_transition = selected_edge.as_ref().is_some_and(|edge_id| {
            self.session
                .graph()
                .edges
                .get(edge_id)
                .and_then(|edge| self.session.graph().nodes.get(&edge.from.node))
                .is_some_and(|node| node.node_type.as_str() == "anim.state")
        });

        if selected_is_state_transition {
            let edge_id = selected_edge.expect("selected transition must still exist");
            self.show_typed_transition_editor(ui, edge_id, &parameters);
        } else {
            self.show_inspector(ui);
        }

        ui.ctx()
            .data_mut(|data| data.insert_temp(state_id, ui_state));
    }

    fn show_animation_parameter_creation(
        &mut self,
        ui: &mut egui::Ui,
        parameters: &[GraphParameter],
        state: &mut GraphParameterUiState,
    ) {
        ui.horizontal(|ui| {
            ui.add(
                egui::TextEdit::singleline(&mut state.new_name).hint_text("speed or grounded"),
            );
            egui::ComboBox::from_id_salt("new_animation_parameter_kind")
                .selected_text(state.new_kind.label())
                .show_ui(ui, |ui| {
                    for kind in GraphParameterKind::ALL {
                        ui.selectable_value(&mut state.new_kind, kind, kind.label());
                    }
                });

            let name = state.new_name.trim();
            let can_add = validate_parameter_name(name).is_ok()
                && !parameters.iter().any(|parameter| parameter.name == name);
            if ui
                .add_enabled(can_add, egui::Button::new("Add Parameter"))
                .clicked()
            {
                let mut updated = parameters.to_vec();
                updated.push(GraphParameter {
                    name: name.to_owned(),
                    kind: state.new_kind,
                });
                match self.set_animation_graph_parameters(&updated) {
                    Ok(()) => state.new_name.clear(),
                    Err(error) => {
                        self.report_error("editor.animation_parameter_update_failed", error)
                    }
                }
            }
        });

        if !state.new_name.trim().is_empty()
            && let Err(error) = validate_parameter_name(&state.new_name) {
                ui.small(error);
            }
    }

    fn apply_animation_parameter_action(
        &mut self,
        action: ParameterAction,
        parameters: &mut Vec<GraphParameter>,
        state: &mut GraphParameterUiState,
    ) -> Result<(), String> {
        match action {
            ParameterAction::Rename { old, new } => {
                validate_parameter_name(&new)?;
                if parameters
                    .iter()
                    .any(|parameter| parameter.name != old && parameter.name == new)
                {
                    return Err(format!("animation parameter `{new}` already exists"));
                }
                let Some(parameter) = parameters
                    .iter_mut()
                    .find(|parameter| parameter.name == old)
                else {
                    return Err(format!("animation parameter `{old}` no longer exists"));
                };
                parameter.name = new.clone();
                self.set_animation_graph_parameters(parameters)?;
                self.rename_transition_parameter(&old, &new)?;
                state.rename_buffers.remove(&old);
                state.rename_buffers.insert(new.clone(), new);
                Ok(())
            }
            ParameterAction::ChangeKind { name, kind } => {
                let Some(parameter) = parameters
                    .iter_mut()
                    .find(|parameter| parameter.name == name)
                else {
                    return Err(format!("animation parameter `{name}` no longer exists"));
                };
                parameter.kind = kind;
                self.clear_transition_conditions_using(&name)?;
                self.set_animation_graph_parameters(parameters)
            }
            ParameterAction::Delete(name) => {
                parameters.retain(|parameter| parameter.name != name);
                self.clear_transition_conditions_using(&name)?;
                state.rename_buffers.remove(&name);
                self.set_animation_graph_parameters(parameters)
            }
        }
    }

    fn set_animation_graph_parameters(
        &mut self,
        parameters: &[GraphParameter],
    ) -> Result<(), String> {
        let entry_id = animation_entry_node(self.session.graph())
            .ok_or_else(|| "Animation Graph has no Entry node".to_owned())?;
        let entry = self
            .session
            .graph()
            .nodes
            .get(&entry_id)
            .ok_or_else(|| "Animation Graph Entry node disappeared".to_owned())?;
        let mut properties = match entry.properties.clone() {
            Value::Object(properties) => properties,
            _ => BTreeMap::new(),
        };
        properties.insert(
            PARAMETERS_PROPERTY.to_owned(),
            animation_parameters_value(parameters),
        );
        self.session
            .set_node_property(entry_id, Value::Object(properties))
            .map_err(|error| error.to_string())
    }

    fn rename_transition_parameter(&mut self, old: &str, new: &str) -> Result<(), String> {
        let replacements = self
            .session
            .graph()
            .edges
            .iter()
            .filter_map(|(edge_id, edge)| {
                let mut condition = transition_condition(edge);
                if condition.parameter() != Some(old) {
                    return None;
                }
                condition.rename_parameter(old, new);
                Some((edge_id.clone(), condition, transition_fade(edge)))
            })
            .collect::<Vec<_>>();

        for (edge_id, condition, fade) in replacements {
            self.session
                .set_animation_transition(edge_id, condition.encode(), fade)
                .map_err(|error| error.to_string())?;
        }
        Ok(())
    }

    fn clear_transition_conditions_using(&mut self, name: &str) -> Result<(), String> {
        let replacements = self
            .session
            .graph()
            .edges
            .iter()
            .filter_map(|(edge_id, edge)| {
                if transition_condition(edge).parameter() == Some(name) {
                    Some((edge_id.clone(), transition_fade(edge)))
                } else {
                    None
                }
            })
            .collect::<Vec<_>>();

        for (edge_id, fade) in replacements {
            self.session
                .set_animation_transition(edge_id, String::new(), fade)
                .map_err(|error| error.to_string())?;
        }
        Ok(())
    }

    fn show_typed_transition_editor(
        &mut self,
        ui: &mut egui::Ui,
        edge_id: EdgeId,
        parameters: &[GraphParameter],
    ) {
        let Some(edge) = self.session.graph().edges.get(&edge_id).cloned() else {
            ui.label("Selected transition is missing");
            return;
        };
        let source_label = self
            .session
            .graph()
            .nodes
            .get(&edge.from.node)
            .map(graph_parameter_node_label)
            .unwrap_or_else(|| edge.from.node.as_str().to_owned());
        let target_label = self
            .session
            .graph()
            .nodes
            .get(&edge.to.node)
            .map(graph_parameter_node_label)
            .unwrap_or_else(|| edge.to.node.as_str().to_owned());

        ui.heading("Transition");
        ui.label(format!("{source_label}  ->  {target_label}"));
        if ui.button("Open Animation Preview").clicked() {
            self.open_animation_preview_window();
        }
        ui.separator();

        let raw_condition = edge_condition_text(&edge);
        let mut condition = transition_condition(&edge);
        if !condition_matches_declaration(&condition, parameters) {
            condition = TypedTransitionCondition::Invalid(raw_condition);
        }

        let selected_name = condition.parameter().map(str::to_owned);
        let selected_label = match &condition {
            TypedTransitionCondition::Always => "Unconditional".to_owned(),
            TypedTransitionCondition::Invalid(_) => {
                "Removed or undeclared condition".to_owned()
            }
            _ => selected_name.clone().unwrap_or_default(),
        };
        let unconditional_selected = matches!(&condition, TypedTransitionCondition::Always);

        ui.label("Parameter");
        let mut replacement = None;
        egui::ComboBox::from_id_salt(("animation_transition_parameter", edge_id.as_str()))
            .selected_text(selected_label)
            .show_ui(ui, |ui| {
                if ui
                    .selectable_label(unconditional_selected, "Unconditional")
                    .clicked()
                {
                    replacement = Some(TypedTransitionCondition::Always);
                }
                for parameter in parameters {
                    let selected = selected_name.as_deref() == Some(parameter.name.as_str());
                    if ui
                        .selectable_label(
                            selected,
                            format!("{} ({})", parameter.name, parameter.kind.label()),
                        )
                        .clicked()
                    {
                        replacement = Some(default_condition(parameter));
                    }
                }
            });

        if let Some(replacement) = replacement {
            condition = replacement;
            self.commit_typed_transition(edge_id.clone(), &condition, transition_fade(&edge));
        }

        if show_condition_value_controls(ui, &edge_id, &mut condition) {
            self.commit_typed_transition(edge_id.clone(), &condition, transition_fade(&edge));
        }

        ui.separator();
        let committed_fade = transition_fade(&edge);
        let mut use_default_fade = committed_fade.is_none();
        if ui
            .checkbox(&mut use_default_fade, "Use Controller default fade")
            .changed()
        {
            let fade = if use_default_fade { None } else { Some(0.2) };
            self.commit_typed_transition(edge_id.clone(), &condition, fade);
        }
        if !use_default_fade {
            let mut fade = committed_fade.unwrap_or(0.2);
            let changed = ui
                .horizontal(|ui| {
                    ui.label("Fade Duration");
                    ui.add(
                        egui::DragValue::new(&mut fade)
                            .range(0.0..=60.0)
                            .speed(0.01)
                            .suffix(" s"),
                    )
                    .changed()
                })
                .inner;
            if changed {
                self.commit_typed_transition(edge_id.clone(), &condition, Some(fade));
            }
        }

        if ui.button("Delete Transition").clicked() {
            let result = self.session.delete_edge(edge_id);
            self.apply_ui_result(result);
        }
    }

    fn commit_typed_transition(
        &mut self,
        edge_id: EdgeId,
        condition: &TypedTransitionCondition,
        fade: Option<f64>,
    ) {
        let result = self
            .session
            .set_animation_transition(edge_id, condition.encode(), fade);
        self.apply_ui_result(result);
    }
}

fn show_animation_parameter_rows(
    ui: &mut egui::Ui,
    parameters: &[GraphParameter],
    state: &mut GraphParameterUiState,
) -> Option<ParameterAction> {
    if parameters.is_empty() {
        ui.label("No parameters declared.");
        return None;
    }

    let mut action = None;
    for parameter in parameters {
        let buffer = state
            .rename_buffers
            .entry(parameter.name.clone())
            .or_insert_with(|| parameter.name.clone());
        ui.push_id(("animation_parameter", &parameter.name), |ui| {
            egui::Frame::group(ui.style()).show(ui, |ui| {
                ui.horizontal(|ui| {
                    ui.text_edit_singleline(buffer);
                    let new_name = buffer.trim();
                    let can_rename = new_name != parameter.name
                        && validate_parameter_name(new_name).is_ok();
                    if ui
                        .add_enabled(can_rename, egui::Button::new("Rename"))
                        .clicked()
                    {
                        action = Some(ParameterAction::Rename {
                            old: parameter.name.clone(),
                            new: new_name.to_owned(),
                        });
                    }

                    let mut selected_kind = parameter.kind;
                    egui::ComboBox::from_id_salt("kind")
                        .selected_text(selected_kind.label())
                        .show_ui(ui, |ui| {
                            for kind in GraphParameterKind::ALL {
                                ui.selectable_value(&mut selected_kind, kind, kind.label());
                            }
                        });
                    if selected_kind != parameter.kind {
                        action = Some(ParameterAction::ChangeKind {
                            name: parameter.name.clone(),
                            kind: selected_kind,
                        });
                    }

                    if ui.small_button("Delete").clicked() {
                        action = Some(ParameterAction::Delete(parameter.name.clone()));
                    }
                });
            });
        });
    }
    action
}

fn show_condition_value_controls(
    ui: &mut egui::Ui,
    edge_id: &EdgeId,
    condition: &mut TypedTransitionCondition,
) -> bool {
    match condition {
        TypedTransitionCondition::Always => {
            ui.small("This transition is taken on the next graph tick.");
            false
        }
        TypedTransitionCondition::Bool { expected, .. } => {
            let before = *expected;
            ui.label("Expected Value");
            ui.horizontal(|ui| {
                ui.selectable_value(expected, true, "true");
                ui.selectable_value(expected, false, "false");
            });
            *expected != before
        }
        TypedTransitionCondition::Float {
            comparison,
            threshold,
            ..
        } => {
            let before_comparison = *comparison;
            let before_threshold = *threshold;
            ui.horizontal(|ui| {
                egui::ComboBox::from_id_salt(("float_comparison", edge_id.as_str()))
                    .selected_text(comparison.token())
                    .show_ui(ui, |ui| {
                        for candidate in FloatComparison::ALL {
                            ui.selectable_value(comparison, candidate, candidate.token());
                        }
                    });
                ui.add(egui::DragValue::new(threshold).speed(0.05));
            });
            *comparison != before_comparison || *threshold != before_threshold
        }
        TypedTransitionCondition::Trigger { .. } => {
            ui.small("The Trigger is consumed only when this transition wins.");
            false
        }
        TypedTransitionCondition::Invalid(raw) => {
            ui.colored_label(
                egui::Color32::YELLOW,
                "Select a declared parameter or Unconditional to replace this old condition.",
            );
            if !raw.is_empty() {
                ui.monospace(raw.as_str());
            }
            false
        }
    }
}

fn animation_entry_node(graph: &engine_authoring::Graph) -> Option<NodeId> {
    graph.nodes.iter().find_map(|(id, node)| {
        if node.node_type.as_str() == "anim.entry" {
            Some(id.clone())
        } else {
            None
        }
    })
}

fn animation_graph_parameters(graph: &engine_authoring::Graph) -> Vec<GraphParameter> {
    let Some(entry_id) = animation_entry_node(graph) else {
        return Vec::new();
    };
    let Some(entry) = graph.nodes.get(&entry_id) else {
        return Vec::new();
    };
    let Value::Object(properties) = &entry.properties else {
        return Vec::new();
    };
    let Some(Value::Array(values)) = properties.get(PARAMETERS_PROPERTY) else {
        return Vec::new();
    };

    values
        .iter()
        .filter_map(|value| {
            let Value::Object(fields) = value else {
                return None;
            };
            let name = match fields.get("name") {
                Some(Value::String(name)) => name.clone(),
                _ => return None,
            };
            let kind = match fields.get("kind") {
                Some(Value::String(kind)) => GraphParameterKind::from_persisted_name(kind)?,
                _ => return None,
            };
            Some(GraphParameter { name, kind })
        })
        .collect()
}

fn animation_parameters_value(parameters: &[GraphParameter]) -> Value {
    Value::Array(
        parameters
            .iter()
            .map(|parameter| {
                Value::Object(BTreeMap::from([
                    ("name".to_owned(), Value::String(parameter.name.clone())),
                    (
                        "kind".to_owned(),
                        Value::String(parameter.kind.persisted_name().to_owned()),
                    ),
                ]))
            })
            .collect(),
    )
}

fn edge_condition_text(edge: &engine_authoring::Edge) -> String {
    match edge.annotations.get("condition") {
        Some(Value::String(value)) => value.clone(),
        _ => String::new(),
    }
}

fn transition_condition(edge: &engine_authoring::Edge) -> TypedTransitionCondition {
    let raw = edge_condition_text(edge);
    parse_typed_transition_condition(&raw)
        .unwrap_or(TypedTransitionCondition::Invalid(raw))
}

fn parse_typed_transition_condition(raw: &str) -> Option<TypedTransitionCondition> {
    let raw = raw.trim();
    if raw.is_empty() {
        return Some(TypedTransitionCondition::Always);
    }
    if let Some(parameter) = raw.strip_prefix("trigger ") {
        validate_parameter_name(parameter).ok()?;
        return Some(TypedTransitionCondition::Trigger {
            parameter: parameter.to_owned(),
        });
    }

    for (token, comparison) in [
        (">=", FloatComparison::GreaterOrEqual),
        ("<=", FloatComparison::LessOrEqual),
        ("==", FloatComparison::Equal),
        ("!=", FloatComparison::NotEqual),
        (">", FloatComparison::Greater),
        ("<", FloatComparison::Less),
    ] {
        let Some((parameter, right)) = raw.split_once(token) else {
            continue;
        };
        let parameter = parameter.trim();
        validate_parameter_name(parameter).ok()?;
        let right = right.trim();

        if comparison == FloatComparison::Equal
            && let Some(expected) = parse_bool_literal(right) {
                return Some(TypedTransitionCondition::Bool {
                    parameter: parameter.to_owned(),
                    expected,
                });
            }

        let threshold = right.parse::<f64>().ok()?;
        if !threshold.is_finite() {
            return None;
        }
        return Some(TypedTransitionCondition::Float {
            parameter: parameter.to_owned(),
            comparison,
            threshold,
        });
    }
    None
}

fn parse_bool_literal(value: &str) -> Option<bool> {
    match value {
        "true" => Some(true),
        "false" => Some(false),
        _ => None,
    }
}

fn condition_matches_declaration(
    condition: &TypedTransitionCondition,
    parameters: &[GraphParameter],
) -> bool {
    match (condition.parameter(), condition.kind()) {
        (None, None) => !matches!(condition, TypedTransitionCondition::Invalid(_)),
        (Some(name), Some(kind)) => parameters
            .iter()
            .any(|parameter| parameter.name == name && parameter.kind == kind),
        _ => false,
    }
}

fn transition_fade(edge: &engine_authoring::Edge) -> Option<f64> {
    match edge.annotations.get("fade_duration") {
        Some(Value::F64(value)) if value.is_finite() && *value >= 0.0 => Some(*value),
        Some(Value::I64(value)) if *value >= 0 => Some(*value as f64),
        Some(Value::U64(value)) => Some(*value as f64),
        _ => None,
    }
}

fn default_condition(parameter: &GraphParameter) -> TypedTransitionCondition {
    match parameter.kind {
        GraphParameterKind::Bool => TypedTransitionCondition::Bool {
            parameter: parameter.name.clone(),
            expected: true,
        },
        GraphParameterKind::Float => TypedTransitionCondition::Float {
            parameter: parameter.name.clone(),
            comparison: FloatComparison::Greater,
            threshold: 0.0,
        },
        GraphParameterKind::Trigger => TypedTransitionCondition::Trigger {
            parameter: parameter.name.clone(),
        },
    }
}

fn validate_parameter_name(name: &str) -> Result<(), String> {
    let name = name.trim();
    if name.is_empty() {
        return Err("Parameter name must not be blank.".to_owned());
    }
    let mut characters = name.chars();
    let first = characters
        .next()
        .expect("a non-empty parameter name has a first character");
    if !(first.is_ascii_alphabetic() || first == '_')
        || characters.any(|character| !(character.is_ascii_alphanumeric() || character == '_'))
    {
        return Err(
            "Use a Rust-style name: letters or underscore first, then letters, digits, or underscore."
                .to_owned(),
        );
    }
    Ok(())
}

fn graph_parameter_node_label(node: &engine_authoring::Node) -> String {
    node.name
        .as_deref()
        .filter(|name| !name.trim().is_empty())
        .unwrap_or(node.node_type.as_str())
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parser_rejects_removed_free_text_bool_forms() {
        assert!(parse_typed_transition_condition("moving").is_none());
        assert!(parse_typed_transition_condition("!grounded").is_none());
    }

    #[test]
    fn parser_accepts_generated_typed_conditions() {
        assert!(matches!(
            parse_typed_transition_condition("grounded == false"),
            Some(TypedTransitionCondition::Bool {
                expected: false,
                ..
            })
        ));
        assert!(matches!(
            parse_typed_transition_condition("speed >= 0.1"),
            Some(TypedTransitionCondition::Float {
                comparison: FloatComparison::GreaterOrEqual,
                ..
            })
        ));
        assert!(matches!(
            parse_typed_transition_condition("trigger attack"),
            Some(TypedTransitionCondition::Trigger { .. })
        ));
    }

    #[test]
    fn undeclared_or_mismatched_parameters_are_rejected() {
        let parameters = vec![GraphParameter {
            name: "speed".to_owned(),
            kind: GraphParameterKind::Float,
        }];
        let undeclared = TypedTransitionCondition::Bool {
            parameter: "moving".to_owned(),
            expected: true,
        };
        let wrong_kind = TypedTransitionCondition::Bool {
            parameter: "speed".to_owned(),
            expected: true,
        };

        assert!(!condition_matches_declaration(&undeclared, &parameters));
        assert!(!condition_matches_declaration(&wrong_kind, &parameters));
    }
}